### ISSUE TITLE
Maven repo not working

### ISSUE THREAD

**Issue by Favorlock** [gpedro/slack-webhook#10]
As mentioned in the title the maven repo is not working.

**Comment by gpedro** [comment]
look this: https://jitpack.io/#gpedro/slack-webhook/slack-webhook-1.0.4

**Comment by thesmith** [comment]
Publishing to sonatype now: https://oss.sonatype.org/content/repositories/releases/net/gpedro/integrations/slack/slack-webhook/1.1.1/
