### ISSUE TITLE
send json and decode on the other end

### ISSUE THREAD

**Issue by sirvon** [gpedro/slack-webhook#11]
Trying to send some json over this wire and parse it back on the other side....
any hints or pointers?

**Comment by gpedro** [comment]
You can fork this repo, comment [this part](https://github.com/gpedro/slack-webhook/blob/master/src/main/java/net/gpedro/integrations/slack/SlackApi.java#L22-L25) and "deploy" using jitpack.io

**Comment by sirvon** [comment]
can you explain what that will do?

it seems it'll allow me to do this:

```java
JSONObject subdata = new JSONObject();
slackService.sendSlackMsg(subdata);
```

I would have thought changing SlackMessage to accept JSONObject would
have been the way...
