### ISSUE TITLE
throw subclass of RuntimeException if send fails

### ISSUE THREAD

**Issue by jgangemi** [gpedro/slack-webhook#16]
could you please throw a subclass of `RuntimeException` in the event a message fails to send? doing this makes it very difficult to distinguish between other `RuntimeExceptions` that may have been thrown in a larger block of code.

thanks!!

**Comment by thesmith** [comment]
Hey, maybe you could provide a PR to show what you're looking for? Providing unchecked wraps for all the checked exceptions isn't great.

TBH I'd rather just re-write the whole API code to use the Jersey 2 client. What's currently there is pretty nasty.

**Comment by jgangemi** [comment]
i like that the library is lean on dependencies, using jersey would pull in a lot of extras.

jodd (http://jodd.org/) is pretty lightweight and offers http and json functionality that you could use and keep dependencies light and small.

i'll see about putting together a PR.

**Comment by jgangemi** [comment]
any chance a release could be cut to roll out this fix?

**Comment by gpedro** [comment]
@jgangemi sorry for the delay

```
<dependency>
  <groupId>net.gpedro.integrations.slack</groupId>
  <artifactId>slack-webhook</artifactId>
  <version>1.1.2</version>
</dependency>
 ```
