### ISSUE TITLE
Missing "ts" attribute

### ISSUE THREAD

**Issue by patricioe** [gpedro/slack-webhook#24]
Source: https://api.slack.com/docs/message-attachments

![image](https://user-images.githubusercontent.com/250893/29340845-06fb6926-81d6-11e7-888e-b128f057d7bd.png)

If I have cycles I can submit a PR but I wanted to flag this missing attribute to start the conversation. Please let me know if I'm missing something.

**Comment by patricioe** [comment]
and `footer` seems to be missing as well.

In the example, the `by Trevor` part comes from the `footer` field.

**Comment by gpedro** [comment]
Can you send a pull-request? :D

**Comment by gpedro** [comment]
Resolved in `v.1.4.0`
