### ISSUE TITLE
How to tag someone

### ISSUE THREAD

**Issue by adriens** [gpedro/slack-webhook#25]
Hi, i'd like to tag (mention) someone while posting from the webhook on a given channel.

It's exactly the same thing as the one described here : https://stackoverflow.com/questions/40771924/how-to-mention-user-in-slack-client

Is it feasible and if it does, could you please provide me some code snippet ?

Thanks in advance for your help.

Best Regards.

**Comment by gpedro** [comment]
Resolved in `v.1.4.0`

**Comment by adriens** [comment]
WOW, great news !!! Thanks a lot for the new feature !!!

**Comment by gpedro** [comment]
Thank you for issue :D 
you`re awesome!

**Comment by adriens** [comment]
Just tested : workeds like a charm !
