### ISSUE TITLE
Central?

### ISSUE THREAD

**Issue by chrylis** [gpedro/slack-webhook#5]
Any chance of getting this library pushed to Central?

**Comment by gpedro** [comment]
idk how i can make this

**Comment by minecrafter** [comment]
:+1: 

@gpedro can use the Sonatype OSS repository: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by gpedro** [comment]
@minecrafter thanks! I'll add there.

**Comment by gpedro** [comment]
Issue created: [OSSRH-13320](https://issues.sonatype.org/browse/OSSRH-13320)

**Comment by chrylis** [comment]
You can see the client I maintain at https://github.com/chrylis/blitline-java-client for an example POM, including the necessary metadata (URL, maintainers, repositories), and the `profile` at the bottom that handles GPG signatures for pushing to Central.

**Comment by gpedro** [comment]
@chrylis 
I would be happy to see a PR for this from you.

**Comment by chrylis** [comment]
I think I can get that done fairly easily.

**Comment by gpedro** [comment]
@chrylis great. i'll waiting for your PR

**Comment by gpedro** [comment]
Pending
- [x] Central Maven
- [ ] @chrylis PR

[OSSRH-13320 (resolved)](https://issues.sonatype.org/browse/OSSRH-13320)

**Comment by borodust** [comment]
Also, I can suggest using bintray. Should be easier to maintan and you can include package into oss repo later, if needed. You can check my fork of your project. If you like the approach, I can arrange a PR of features you like to be merged back into your project.

**Comment by chrylis** [comment]
Bintray is fine, but it's a non-default repository for Maven and (I think) Grape, so it's a both-and rather than an either-or.

**Comment by gpedro** [comment]
```xml
<dependency>
  <groupId>net.gpedro.integrations.slack</groupId>
  <artifactId>slack-webhook</artifactId>
  <version>1.0.3</version>
</dependency>
```

**Comment by minecrafter** [comment]
It doesn't appear resolved, search.maven.org doesn't turn up with this library.

**Comment by chrylis** [comment]
minecrafter's right. Make sure that you closed and then released the staging repository on OSSRH.

**Comment by gpedro** [comment]
@chrylis @minecrafter try again.

**Comment by minecrafter** [comment]
Looks to be good now.

**Comment by chrylis** [comment]
That's a snapshot, but not a release, and snapshots aren't synced to Central. You'll need to have a non-`SNAPSHOT` Maven version, then run `mvn deploy -DperformRelease`, log in to the OSSRH Nexus interface, select your repository, close it, wait a few seconds, then release it.

**Comment by BerndErnst** [comment]
+1 for chrylis

**Comment by rlemaitre** [comment]
+1 for chrylis too

**Comment by gpedro** [comment]
i will solve this issue today.

**Comment by thesmith** [comment]
Can you add my sonatype user 'thesmith' as an authorized deployer so I can help get the release out?

**Comment by thesmith** [comment]
Ok, it's released now : https://oss.sonatype.org/content/repositories/releases/net/gpedro/integrations/slack/slack-webhook/1.1.1/

For reference, to release the project you need to prepare and perform the release using the 'release-sign-artifacts' profile:

    mvn -Prelease-sign-artifacts release:prepare release:perform

Obviously make sure you've set up your sonatype and gpg settings.
