### ISSUE TITLE
Is there any possibility to add unfurling to Messages?

### ISSUE THREAD

**Issue by BerndErnst** [gpedro/slack-webhook#7]
I want to add 
"unfurl_media": true
"unfurl_links": true
to my SlackMessage.
Is there any way to do it?

Source:
https://api.slack.com/docs/unfurling

**Comment by gpedro** [comment]
You can add variables in [line 18](https://github.com/gpedro/slack-webhook/blob/master/src/main/java/net/gpedro/integrations/slack/SlackMessage.java#L18), create setter at bottom and add property in [line 71](https://github.com/gpedro/slack-webhook/blob/master/src/main/java/net/gpedro/integrations/slack/SlackMessage.java#L71)

**Comment by BerndErnst** [comment]
Thx for the fast response.
Why you don't add it to your source?

**Comment by gpedro** [comment]
I'll add.
