### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by prudencioj** [gpedro/slack-webhook#8]
Is it published in maven central or other repository?

**Comment by jitpack-io** [comment]
Didn't appear on mvn central search so maybe this will help: https://jitpack.io/#gpedro/slack-webhook/slack-webhook-1.0.4

**Comment by thesmith** [comment]
https://oss.sonatype.org/content/repositories/releases/net/gpedro/integrations/slack/slack-webhook/1.1.1/
